In [60]:
import pandas as pd
import numpy as np

In [61]:
# Load Kaggle 'games.csv'
games = pd.read_csv('../data/raw/game.csv')

games.head()

,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,fgm_home,...,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,plus_minus_away,video_available_away,season_type
0,21946,1610610035,HUS,Toronto Huskies,24600001,1946-11-01 00:00:00,HUS vs. NYK,L,0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,68.0,2,0,Regular Season
1,21946,1610610034,BOM,St. Louis Bombers,24600003,1946-11-02 00:00:00,BOM vs. PIT,W,0,20.0,...,NaN,NaN,NaN,NaN,NaN,25.0,51.0,-5,0,Regular Season
2,21946,1610610032,PRO,Providence Steamrollers,24600002,1946-11-02 00:00:00,PRO vs. BOS,W,0,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,-6,0,Regular Season
3,21946,1610610025,CHS,Chicago Stags,24600004,1946-11-02 00:00:00,CHS vs. NYK,W,0,21.0,...,NaN,NaN,NaN,NaN,NaN,22.0,47.0,-16,0,Regular Season
4,21946,1610610028,DEF,Detroit Falcons,24600005,1946-11-02 00:00:00,DEF vs. WAS,L,0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,50.0,17,0,Regular Season

In [62]:
games['game_date'] = pd.to_datetime(games['game_date'], errors='coerce')

In [63]:
games = games.dropna(subset=['pts_home', 'pts_away'])

In [64]:
games['home_win'] = (games['pts_home'] > games['pts_away']).astype(int)
games['home_win'].value_counts()

home_win
1    40652
0    25046
Name: count, dtype: int64

In [65]:
games.info()
games.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65698 entries, 0 to 65697
Data columns (total 56 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   season_id               65698 non-null  int64
 1   team_id_home            65698 non-null  int64
 2   team_abbreviation_home  65698 non-null  object
 3   team_name_home          65698 non-null  object
 4   game_id                 65698 non-null  int64
 5   game_date               65698 non-null  datetime64[ns]
 6   matchup_home            65698 non-null  object
 7   wl_home                 65696 non-null  object
 8   min                     65698 non-null  int64
 9   fgm_home                65685 non-null  float64
 10  fga_home                50251 non-null  float64
 11  fg_pct_home             50208 non-null  float64
 12  fg3m_home               52480 non-null  float64
 13  fg3a_home               47015 non-null  float64
 14  fg3_pct_home            46624 non-null  float64
 15  ftm_home                65682 non-null  float64
 16  fta_home                62694 non-null  float64
 17  ft_pct_home             62689 non-null  float64
 18  oreb_home               46762 non-null  float64
 19  dreb_home               46699 non-null  float64
 20  reb_home                49969 non-null  float64
 21  ast_home                49893 non-null  float64
 22  stl_home                46849 non-null  float64
 23  blk_home                47072 non-null  float64
 24  tov_home                47014 non-null  float64
 25  pf_home                 62842 non-null  float64
 26  pts_home                65698 non-null  float64
 27  plus_minus_home         65698 non-null  int64
 28  video_available_home    65698 non-null  int64
 29  team_id_away            65698 non-null  int64
 30  team_abbreviation_away  65698 non-null  object
 31  team_name_away          65698 non-null  object
 32  matchup_away            65698 non-null  object
 33  wl_away                 65696 non-null  object
 34  fgm_away                65685 non-null  float64
 35  fga_away                50251 non-null  float64
 36  fg_pct_away             50209 non-null  float64
 37  fg3m_away               52480 non-null  float64
 38  fg3a_away               47015 non-null  float64
 39  fg3_pct_away            46736 non-null  float64
 40  ftm_away                65685 non-null  float64
 41  fta_away                62694 non-null  float64
 42  ft_pct_away             62692 non-null  float64
 43  oreb_away               46762 non-null  float64
 44  dreb_away               46700 non-null  float64
 45  reb_away                49973 non-null  float64
 46  ast_away                49897 non-null  float64
 47  stl_away                46849 non-null  float64
 48  blk_away                47073 non-null  float64
 49  tov_away                47013 non-null  float64
 50  pf_away                 62847 non-null  float64
 51  pts_away                65698 non-null  float64
 52  plus_minus_away         65698 non-null  int64
 53  video_available_away    65698 non-null  int64
 54  season_type             65698 non-null  object
 55  home_win                65698 non-null  int32
dtypes: datetime64[ns](1), float64(36), int32(1), int64(9), object(9)
memory usage: 27.8+ MB

,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,fgm_home,...,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,plus_minus_away,video_available_away,season_type,home_win
count,65698.000000,6.569800e+04,65698,65698,6.569800e+04,65698,65698,65696,65698.000000,65685.000000,...,49897.000000,46849.000000,47073.000000,47013.000000,62847.000000,65698.000000,65698.000000,65698.000000,65698,65698.000000
unique,NaN,NaN,97,98,NaN,NaN,2292,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN
top,NaN,NaN,BOS,Boston Celtics,NaN,NaN,BOS vs. NYK,W,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Regular Season,NaN
freq,NaN,NaN,3124,3124,NaN,NaN,258,40649,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60192,NaN
mean,22949.338747,1.609926e+09,NaN,NaN,2.584747e+07,1995-02-15 15:13:23.202532736,NaN,NaN,221.003486,39.672269,...,22.135419,7.854148,4.681537,15.199860,23.097284,100.991567,-3.627569,0.201330,NaN,0.618771
min,12005.000000,4.500000e+01,NaN,NaN,1.050000e+07,1946-11-01 00:00:00,NaN,NaN,0.000000,4.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,19.000000,-73.000000,0.000000,NaN,0.000000
25%,21981.000000,1.610613e+09,NaN,NaN,2.130053e+07,1982-12-15 06:00:00,NaN,NaN,240.000000,35.000000,...,18.000000,6.000000,3.000000,12.000000,20.000000,92.000000,-12.000000,0.000000,NaN,0.000000
50%,21997.000000,1.610613e+09,NaN,NaN,2.630007e+07,1997-11-06 00:00:00,NaN,NaN,240.000000,40.000000,...,22.000000,8.000000,4.000000,15.000000,23.000000,101.000000,-4.000000,0.000000,NaN,1.000000
75%,22011.000000,1.610613e+09,NaN,NaN,2.880069e+07,2010-04-07 00:00:00,NaN,NaN,240.000000,44.000000,...,26.000000,10.000000,6.000000,18.000000,26.000000,110.000000,5.000000,0.000000,NaN,1.000000
max,42022.000000,1.610617e+09,NaN,NaN,4.980009e+07,2023-06-12 00:00:00,NaN,NaN,365.000000,84.000000,...,89.000000,27.000000,19.000000,40.000000,115.000000,196.000000,68.000000,1.000000,NaN,1.000000
std,5000.305500,3.324313e+07,NaN,NaN,6.303760e+06,NaN,NaN,NaN,67.903521,6.770802,...,5.380805,3.031766,2.500820,4.299798,5.227208,14.418755,13.091395,0.400997,NaN,0.485692

In [66]:
games.to_csv('../data/clean/clean_game.csv', index=False)